### ISSUE TITLE
CloudFlare doesn't work

### ISSUE THREAD

**Issue by ghost** [james3126/CloudflareDDNSUpdater#3]
I use raspberry pi 3B+  buster os, runs:
$ python3 CloudFlareDDNSUpdater.py

Check completed, update reqired! (Old IP: 113.116.89.86, New IP: 113.116.89.86)
Traceback (most recent call last):
  File "CloudFlareDDNSUpdater.py", line 291, in <module>
    update_record(ZONE_ID, WEB_ADDRESS, CURRENT_IP, EMAIL, API_KEY, IDENTIFIER, HEADERS, PROXIED) #HERE
  File "CloudFlareDDNSUpdater.py", line 170, in update_record
    r_status, r_reason = request.put(UPDATE_A_NAME_RECORD_URL, data=PAYLOAD, headers=HEADERS)
  File "/home/tim813/CloudflareDDNSUpdater-master/reqs.py", line 34, in put
    response = urllib.request.urlopen(req)
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized

Could you tell me how to fix it, Thanks a lot

**Comment by james3126** [comment]
Hi there, apologies for the late reply. I assume you've resolved this, or moved on by now.

Judging by the http 401 error while trying to run updates to the API, it's possible you've run into a 'challenge' by CloudFlare. This was found to be the case with a previous 401 API response [https://community.cloudflare.com/t/401-status-when-trying-to-create-a-rest-api-connection/84500](url)

Does the issue still occur when re-running?
